// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWY2gK_wZBDXiN1sMJfkWxV2Fv2eXfb14',
    appId: '1:394868933088:web:b8c7cf9e529d7ea637eb85',
    messagingSenderId: '394868933088',
    projectId: 'direct-booking-app-754d8',
    authDomain: 'direct-booking-app-754d8.firebaseapp.com',
    storageBucket: 'direct-booking-app-754d8.firebasestorage.app',
    measurementId: 'G-RRD7ZXFLEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYueGZUbYcMR6EDWx8moOnfQ4AL4I4vkg',
    appId: '1:394868933088:android:1e25fa0097a664f537eb85',
    messagingSenderId: '394868933088',
    projectId: 'direct-booking-app-754d8',
    storageBucket: 'direct-booking-app-754d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZOFIY5flvzBNio2rtQxd3DDtw_UZeYfs',
    appId: '1:394868933088:ios:87fd72f60551069337eb85',
    messagingSenderId: '394868933088',
    projectId: 'direct-booking-app-754d8',
    storageBucket: 'direct-booking-app-754d8.firebasestorage.app',
    iosBundleId: 'com.example.directBookingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZOFIY5flvzBNio2rtQxd3DDtw_UZeYfs',
    appId: '1:394868933088:ios:87fd72f60551069337eb85',
    messagingSenderId: '394868933088',
    projectId: 'direct-booking-app-754d8',
    storageBucket: 'direct-booking-app-754d8.firebasestorage.app',
    iosBundleId: 'com.example.directBookingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWY2gK_wZBDXiN1sMJfkWxV2Fv2eXfb14',
    appId: '1:394868933088:web:73f965809af76cbf37eb85',
    messagingSenderId: '394868933088',
    projectId: 'direct-booking-app-754d8',
    authDomain: 'direct-booking-app-754d8.firebaseapp.com',
    storageBucket: 'direct-booking-app-754d8.firebasestorage.app',
    measurementId: 'G-STFNZSGX5B',
  );

}
